In [1]:
# ======================================================
# FAKE NEWS DETECTION USING MACHINE LEARNING
# ======================================================

# ==========================
# IMPORT LIBRARIES
# ==========================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report




In [2]:
# ==========================
# LOAD DATASET
# ==========================

df = pd.read_csv("news.csv")


# ==========================
# DISPLAY FIRST 5 ROWS
# ==========================

print("\n==============================")
print("FIRST 5 ROWS OF DATASET")
print("==============================\n")

print(df.head())


# ==========================
# DATASET INFORMATION
# ==========================

print("\n==============================")
print("DATASET SHAPE")
print("==============================\n")

print(df.shape)


print("\n==============================")
print("COLUMN NAMES")
print("==============================\n")

print(df.columns)


print("\n==============================")
print("CHECKING MISSING VALUES")
print("==============================\n")

print(df.isnull().sum())


# ==========================
# REMOVE NULL VALUES
# ==========================

df = df.dropna()





FIRST 5 ROWS OF DATASET

                                               title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017  

DATASET SHAPE

(23481, 4)

COLUMN NAMES

Index(['title', 'text', 'subject', 'date'], dtype='object')

CHECKING MI

In [7]:
# ==========================
# CREATE INPUT DATA
# ==========================

# Combine title and author
df["content"] = df["title"] + " " + df["text"]

# Input Features
X = df["content"]

# Output Labels
y = df["subject"]





In [8]:
# ==========================
# SPLIT DATASET
# ==========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)



In [9]:
# ==========================
# TEXT VECTORIZATION
# ==========================

tfidf_vectorizer = TfidfVectorizer(
    stop_words="english",
    max_df=0.7
)

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

X_test_tfidf = tfidf_vectorizer.transform(X_test)


In [10]:
# ==========================
# CREATE MODEL
# ==========================

model = PassiveAggressiveClassifier(max_iter=50)


# ==========================
# TRAIN MODEL
# ==========================

model.fit(X_train_tfidf, y_train)


# ==========================
# PREDICTION
# ==========================

y_pred = model.predict(X_test_tfidf)




In [11]:
# ==========================
# ACCURACY SCORE
# ==========================

score = accuracy_score(y_test, y_pred)

print("\n==============================")
print("MODEL ACCURACY")
print("==============================\n")

print("Accuracy:", round(score * 100, 2), "%")





MODEL ACCURACY

Accuracy: 51.65 %


In [12]:
# ==========================
# CONFUSION MATRIX
# ==========================

cm = confusion_matrix(y_test, y_pred)

print("\n==============================")
print("CONFUSION MATRIX")
print("==============================\n")

print(cm)


# ==========================
# CLASSIFICATION REPORT
# ==========================

print("\n==============================")
print("CLASSIFICATION REPORT")
print("==============================\n")

print(classification_report(y_test, y_pred))





CONFUSION MATRIX

[[  18    0    4    0  122  172]
 [   0   21    1  135    1    1]
 [   2    0 1798    0   13    8]
 [   0  145    1   12    1    1]
 [  63    0   10    2  142  680]
 [ 142    0   25    4  738  435]]

CLASSIFICATION REPORT

                 precision    recall  f1-score   support

Government News       0.08      0.06      0.07       316
    Middle-east       0.13      0.13      0.13       159
           News       0.98      0.99      0.98      1821
        US_News       0.08      0.07      0.08       160
      left-news       0.14      0.16      0.15       897
       politics       0.34      0.32      0.33      1344

       accuracy                           0.52      4697
      macro avg       0.29      0.29      0.29      4697
   weighted avg       0.51      0.52      0.51      4697



In [ ]:
# ==========================
# CUSTOM NEWS PREDICTION
# ==========================

while True:

    print("\n==============================")
    print("FAKE NEWS DETECTOR")
    print("==============================")

    news = input("\nEnter News Headline: ")

    # Exit condition
    if news.upper() == "EXIT":
        print("\nProgram Ended")
        break

    # Convert news text into vector
    news_vector = tfidf_vectorizer.transform([news])

    # Predict
    prediction = model.predict(news_vector)

    # Output result
    if prediction[0] == 1:
        print("\nPrediction: REAL NEWS")
    else:
        print("\nPrediction: FAKE NEWS")


FAKE NEWS DETECTOR



Enter News Headline:  Government gives every citizen free gold



Prediction: FAKE NEWS

FAKE NEWS DETECTOR
